[[pages]]
path = "app.py"
name = "Charging-Hub"
icon = "ğŸ "

[[pages]]
path = "_pages/search.py"
name = "Search"
icon = "ğŸ”"

[[pages]]
path = "_pages/stations.py"
name = "Charging station"
icon = "ğŸ“–"
